export const ROLES = {
  STUDENT: 'student',
  FACULTY: 'faculty',
  REGISTRAR: 'registrar',
};

export const INITIAL_USERS = {
  [ROLES.STUDENT]: {
    name: 'Aisha Sharma',
    id: 'MU-2023-CS-0842',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    email: 'aisha.sharma@meridian.edu',
    phone: '+91 98450 12842',
    department: 'School of Computing & Data Sciences',
    program: 'B.Tech Computer Science & Engineering',
    semester: 'Semester VI (Spring 2026)',
    advisor: 'Prof. Raghav Iyer',
    status: 'Good Standing',
    cgpa: '3.88',
    sgpa: '3.92',
    attendance: '91.4%',
    balance: '₹65,000',
    creditsCompleted: 104,
    totalCredits: 140,
    hostel: 'Kaveri Residence Quad, #312',
    emergencyContact: 'Rajesh Sharma (+91 98200 44321)',
  },
  [ROLES.FACULTY]: {
    name: 'Prof. Raghav Iyer',
    id: 'FAC-ENG-108',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    email: 'raghav.iyer@meridian.edu',
    phone: '+91 94480 55108',
    department: 'Computer Science & Engineering',
    designation: 'Professor & Course Director',
    office: 'Aryabhata Block, Room 412',
    coursesCount: 3,
    studentsCount: 174,
    officeHours: 'Tue & Thu 2:00 PM – 4:30 PM',
    qualification: 'Ph.D. Distributed Systems (IISc Bangalore)',
  },
  [ROLES.REGISTRAR]: {
    name: 'Ms. Fernandes',
    id: 'REG-ADM-004',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    email: 'c.fernandes@meridian.edu',
    phone: '+91 80 2844 0004',
    department: 'Office of the Registrar & Academic Governance',
    designation: 'University Registrar & Controller of Examinations',
    office: 'Senate Secretariat, Central Admin 101',
    activeCampusTerm: 'Spring 2026 (Week 9)',
    totalCampuses: 3,
    accreditationStatus: 'NAAC A++ / NIRF Top 15',
  },
};

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    title: 'Midterm Exam Hall Tickets Released',
    message: 'Spring 2026 Midterm seating allocations are now available in Academic Records.',
    type: 'academic',
    time: '15 mins ago',
    unread: true,
  },
  {
    id: 'notif-2',
    title: 'Semester VI Fee Due Reminder',
    message: 'Tuition installment 2 (₹65,000) is scheduled for clearance before October 15, 2026.',
    type: 'financial',
    time: '2 hours ago',
    unread: true,
  },
  {
    id: 'notif-3',
    title: 'Attendance Advisory Notice',
    message: 'Biometric turnstile sync complete. Overall campus student attendance stands at 91.2%.',
    type: 'attendance',
    time: '5 hours ago',
    unread: false,
  },
  {
    id: 'notif-4',
    title: 'Distinguished Lecture on Cloud Architecture',
    message: 'Special session with visiting industry architects in Ramanujan Auditorium this Friday.',
    type: 'general',
    time: '1 day ago',
    unread: false,
  },
  {
    id: 'notif-5',
    title: 'CS-302 Gradebook Update',
    message: 'Prof. Raghav Iyer has posted continuous assessment scores for Distributed Systems.',
    type: 'grade',
    time: '2 days ago',
    unread: false,
  },
];

export const INITIAL_STUDENT_COURSES = [
  {
    code: 'CS-302',
    name: 'Distributed Systems & Cloud Computing',
    instructor: 'Prof. Raghav Iyer',
    credits: 4,
    room: 'Aryabhata 304',
    attendancePercent: 94.2,
    attended: 33,
    total: 35,
    safeLeaves: 6,
    status: 'Excellent',
    gradePrediction: 'A',
    schedule: 'Mon, Wed 10:00 AM - 11:30 AM',
  },
  {
    code: 'CS-306',
    name: 'Modern Database Internals & Storage',
    instructor: 'Prof. Ananya Roy',
    credits: 4,
    room: 'Ada Lovelace Lab B',
    attendancePercent: 88.5,
    attended: 23,
    total: 26,
    safeLeaves: 3,
    status: 'Good',
    gradePrediction: 'A-',
    schedule: 'Tue, Thu 09:00 AM - 10:30 AM',
  },
  {
    code: 'CS-314',
    name: 'Applied Cryptography & Network Security',
    instructor: 'Dr. Julian Thorne',
    credits: 3,
    room: 'Bhabha Auditorium',
    attendancePercent: 96.0,
    attended: 24,
    total: 25,
    safeLeaves: 5,
    status: 'Excellent',
    gradePrediction: 'A+',
    schedule: 'Mon, Fri 01:30 PM - 03:00 PM',
  },
  {
    code: 'AI-280',
    name: 'Neural Networks & Deep Learning',
    instructor: 'Dr. Sarah Lin',
    credits: 4,
    room: 'Turing Lab 102',
    attendancePercent: 84.6,
    attended: 22,
    total: 26,
    safeLeaves: 2,
    status: 'Attention',
    gradePrediction: 'B+',
    schedule: 'Wed, Fri 11:45 AM - 01:15 PM',
  },
  {
    code: 'HSS-210',
    name: 'Technology Ethics, Cyber Law & IPR',
    instructor: 'Prof. David Sterling',
    credits: 3,
    room: 'Humanities Hall 12',
    attendancePercent: 93.3,
    attended: 14,
    total: 15,
    safeLeaves: 2,
    status: 'Good',
    gradePrediction: 'A',
    schedule: 'Thu 02:00 PM - 04:30 PM',
  },
];

export const INITIAL_STUDENT_FEES = {
  currentSemester: {
    term: 'Spring 2026 (Semester VI)',
    totalPayable: 340000,
    paidAmount: 275000,
    outstanding: 65000,
    dueDate: 'October 15, 2026',
    status: 'Partial Due (₹65,000)',
    breakdown: [
      { category: 'Tuition & Academic Instruction (18 Credits)', amount: 240000, status: 'Paid' },
      { category: 'Advanced Computing Lab, Cloud GPU & AWS Fund', amount: 45000, status: 'Paid' },
      { category: 'Campus Health Center & Student Insurance', amount: 15000, status: 'Unpaid' },
      { category: 'Digital Library, IEEE & ACM Consortium Access', amount: 15000, status: 'Unpaid' },
      { category: 'Sports, Cultural & Student Life Facilities', amount: 25000, status: 'Unpaid' },
    ],
  },
  history: [
    { receipt: 'REC-2026-0891', date: '12 Jan 2026', term: 'Spring 2026 (Installment 1)', amount: 275000, method: 'Campus NetBanking (SBI)', status: 'Cleared' },
    { receipt: 'REC-2025-0914', date: '24 Aug 2025', term: 'Fall 2025 (Semester V)', amount: 330000, method: 'UPI / HDFC NetBanking', status: 'Cleared' },
    { receipt: 'REC-2025-0122', date: '18 Jan 2025', term: 'Spring 2025 (Semester IV)', amount: 320000, method: 'National Electronic Wire (NEFT)', status: 'Cleared' },
    { receipt: 'REC-2024-0803', date: '19 Aug 2024', term: 'Fall 2024 (Semester III)', amount: 310000, method: 'Campus NetBanking', status: 'Cleared' },
  ],
};

export const INITIAL_TIMETABLE = {
  Monday: [
    { time: '09:00 - 10:00 AM', code: 'CS-314', name: 'Applied Cryptography', room: 'Bhabha Aud.', instructor: 'Dr. Julian Thorne', type: 'Lecture' },
    { time: '10:00 - 11:30 AM', code: 'CS-302', name: 'Distributed Systems', room: 'Aryabhata 304', instructor: 'Prof. Raghav Iyer', type: 'Core' },
    { time: '12:00 - 01:00 PM', code: 'LUNCH', name: 'Campus Commons & Dining', room: 'Student Center', instructor: 'Campus Amenities', type: 'Break' },
    { time: '01:30 - 03:00 PM', code: 'CS-314', name: 'Network Security Lab Practicum', room: 'Cyber Lab 4', instructor: 'Dr. Julian Thorne', type: 'Lab' },
  ],
  Tuesday: [
    { time: '09:00 - 10:30 AM', code: 'CS-306', name: 'Modern Database Internals', room: 'Ada Lab B', instructor: 'Prof. Ananya Roy', type: 'Core' },
    { time: '11:00 - 12:30 PM', code: 'RES-01', name: 'Undergraduate Research Colloquium', room: 'Central Library 3F', instructor: 'Prof. Raghav Iyer', type: 'Seminar' },
    { time: '02:00 - 03:30 PM', code: 'CS-302', name: 'Cloud Architecture Hands-on', room: 'Aryabhata 304', instructor: 'Prof. Raghav Iyer', type: 'Tutorial' },
  ],
  Wednesday: [
    { time: '10:00 - 11:30 AM', code: 'CS-302', name: 'Distributed Systems', room: 'Aryabhata 304', instructor: 'Prof. Raghav Iyer', type: 'Core' },
    { time: '11:45 - 01:15 PM', code: 'AI-280', name: 'Deep Learning & Neural Nets', room: 'Turing Lab 102', instructor: 'Dr. Sarah Lin', type: 'Core' },
    { time: '02:30 - 04:00 PM', code: 'MENTOR', name: 'Faculty Advising & Office Hours', room: 'Aryabhata 412', instructor: 'Prof. Raghav Iyer', type: 'Advising' },
  ],
  Thursday: [
    { time: '09:00 - 10:30 AM', code: 'CS-306', name: 'Modern Database Internals', room: 'Ada Lab B', instructor: 'Prof. Ananya Roy', type: 'Core' },
    { time: '11:00 - 12:00 PM', code: 'LIB-WK', name: 'Capstone Group Collaboration', room: 'Innovation Pod 8', instructor: 'Self Managed', type: 'Self Study' },
    { time: '02:00 - 04:30 PM', code: 'HSS-210', name: 'Tech Ethics, Cyber Law & IPR', room: 'Humanities 12', instructor: 'Prof. David Sterling', type: 'Elective' },
  ],
  Friday: [
    { time: '11:45 - 01:15 PM', code: 'AI-280', name: 'Deep Learning & Neural Nets', room: 'Turing Lab 102', instructor: 'Dr. Sarah Lin', type: 'Core' },
    { time: '01:30 - 03:00 PM', code: 'CS-314', name: 'Applied Cryptography', room: 'Bhabha Aud.', instructor: 'Dr. Julian Thorne', type: 'Lecture' },
    { time: '03:30 - 05:00 PM', code: 'CLUB', name: 'Meridian Open Source & ACM Student Chapter', room: 'Innovation Hub', instructor: 'ACM Meridian', type: 'Activity' },
  ],
};

export const INITIAL_STUDENT_TRANSCRIPT = [
  {
    sem: 'Semester I (Fall 2023)',
    sgpa: '3.75',
    credits: 20,
    status: 'Completed',
    courses: [
      { code: 'MATH-101', name: 'Calculus & Linear Algebra', grade: 'A', credits: 4, points: 4.0 },
      { code: 'PHY-102', name: 'Semiconductor Physics', grade: 'A-', credits: 4, points: 3.7 },
      { code: 'CS-101', name: 'Object-Oriented Programming (C++)', grade: 'A', credits: 4, points: 4.0 },
      { code: 'ENG-101', name: 'Technical Communication & Rhetoric', grade: 'A', credits: 4, points: 4.0 },
      { code: 'CS-102L', name: 'Unix & Systems Engineering Lab', grade: 'A+', credits: 4, points: 4.0 },
    ],
  },
  {
    sem: 'Semester II (Spring 2024)',
    sgpa: '3.82',
    credits: 20,
    status: 'Completed',
    courses: [
      { code: 'MATH-102', name: 'Discrete Structures & Graph Theory', grade: 'A', credits: 4, points: 4.0 },
      { code: 'CS-104', name: 'Data Structures & Algorithms', grade: 'A', credits: 4, points: 4.0 },
      { code: 'CS-106', name: 'Digital Logic & Computer Architecture', grade: 'B+', credits: 4, points: 3.3 },
      { code: 'CHEM-105', name: 'Materials Science in Computing', grade: 'A-', credits: 4, points: 3.7 },
      { code: 'HSS-101', name: 'Macroeconomics & Public Policy', grade: 'A', credits: 4, points: 4.0 },
    ],
  },
  {
    sem: 'Semester III (Fall 2024)',
    sgpa: '3.90',
    credits: 22,
    status: 'Completed',
    courses: [
      { code: 'CS-201', name: 'Design & Analysis of Algorithms', grade: 'A+', credits: 4, points: 4.0 },
      { code: 'CS-203', name: 'Operating Systems & Concurrency', grade: 'A', credits: 4, points: 4.0 },
      { code: 'CS-205', name: 'Theory of Computation & Automata', grade: 'A', credits: 4, points: 4.0 },
      { code: 'STAT-201', name: 'Probability & Statistical Inference', grade: 'A-', credits: 4, points: 3.7 },
      { code: 'CS-207L', name: 'Full-Stack Software Engineering Lab', grade: 'A+', credits: 6, points: 4.0 },
    ],
  },
  {
    sem: 'Semester IV (Spring 2025)',
    sgpa: '3.95',
    credits: 22,
    status: 'Completed',
    courses: [
      { code: 'CS-202', name: 'Computer Networks & Protocols', grade: 'A', credits: 4, points: 4.0 },
      { code: 'CS-204', name: 'Compiler Engineering & ASTs', grade: 'A+', credits: 4, points: 4.0 },
      { code: 'CS-206', name: 'Database Management Systems', grade: 'A+', credits: 4, points: 4.0 },
      { code: 'MATH-204', name: 'Numerical Optimization Methods', grade: 'A', credits: 4, points: 4.0 },
      { code: 'AI-201', name: 'Foundations of Artificial Intelligence', grade: 'A', credits: 6, points: 4.0 },
    ],
  },
  {
    sem: 'Semester V (Fall 2025)',
    sgpa: '3.96',
    credits: 20,
    status: 'Completed',
    courses: [
      { code: 'CS-301', name: 'Cloud Native & Microservice Architecture', grade: 'A+', credits: 4, points: 4.0 },
      { code: 'CS-303', name: 'Parallel & High-Performance Computing', grade: 'A', credits: 4, points: 4.0 },
      { code: 'AI-250', name: 'Computer Vision & Representation', grade: 'A', credits: 4, points: 4.0 },
      { code: 'HSS-205', name: 'Organizational Psychology', grade: 'A', credits: 4, points: 4.0 },
      { code: 'RES-301', name: 'Junior Capstone Project (Part 1)', grade: 'A+', credits: 4, points: 4.0 },
    ],
  },
];

export const INITIAL_FACULTY_ROSTER = [
  { id: 'S01', roll: 'MU-2023-CS-0842', name: 'Aisha Sharma', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150', status: 'Present', streak: 12, overall: '94.2%', program: 'B.Tech CSE', email: 'aisha.sharma@meridian.edu' },
  { id: 'S02', roll: 'MU-2023-CS-0811', name: 'Kavya Ramanathan', avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=150', status: 'Present', streak: 4, overall: '88.0%', program: 'B.Tech CSE', email: 'kavya.r@meridian.edu' },
  { id: 'S03', roll: 'MU-2023-CS-0824', name: 'Rohan Mehra', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=150', status: 'Present', streak: 18, overall: '98.1%', program: 'B.Tech CSE', email: 'rohan.m@meridian.edu' },
  { id: 'S04', roll: 'MU-2023-CS-0833', name: 'Aditya Deshmukh', avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&q=80&w=150', status: 'Absent', streak: 0, overall: '74.2%', program: 'B.Tech CSE', email: 'aditya.d@meridian.edu' },
  { id: 'S05', roll: 'MU-2023-CS-0850', name: 'Meera Nambiar', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150', status: 'Present', streak: 8, overall: '91.5%', program: 'B.Tech CSE', email: 'meera.n@meridian.edu' },
  { id: 'S06', roll: 'MU-2023-CS-0862', name: 'Arjun Sen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150', status: 'Late', streak: 2, overall: '82.0%', program: 'B.Tech CSE', email: 'arjun.sen@meridian.edu' },
  { id: 'S07', roll: 'MU-2023-CS-0871', name: 'Pooja Hegde', avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=150', status: 'Present', streak: 15, overall: '96.4%', program: 'B.Tech CSE', email: 'pooja.h@meridian.edu' },
  { id: 'S08', roll: 'MU-2023-CS-0888', name: 'Varun Grover', avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&q=80&w=150', status: 'Present', streak: 6, overall: '89.3%', program: 'B.Tech CSE', email: 'varun.g@meridian.edu' },
  { id: 'S09', roll: 'MU-2023-CS-0895', name: 'Siddharth Rao', avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=150', status: 'Excused', streak: 9, overall: '92.0%', program: 'B.Tech CSE', email: 'sid.rao@meridian.edu' },
  { id: 'S10', roll: 'MU-2023-CS-0902', name: 'Tanvi Joshi', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=150', status: 'Present', streak: 11, overall: '95.0%', program: 'B.Tech CSE', email: 'tanvi.j@meridian.edu' },
];

export const INITIAL_GRADEBOOK = [
  { id: 'G01', roll: 'MU-2023-CS-0842', name: 'Aisha Sharma', midterm: 29.0, quiz: 14.5, project: 38.5, lab: 15.0, total: 97.0, grade: 'A+' },
  { id: 'G02', roll: 'MU-2023-CS-0811', name: 'Kavya Ramanathan', midterm: 24.0, quiz: 12.0, project: 32.0, lab: 13.0, total: 81.0, grade: 'B+' },
  { id: 'G03', roll: 'MU-2023-CS-0824', name: 'Rohan Mehra', midterm: 28.5, quiz: 15.0, project: 37.0, lab: 14.5, total: 95.0, grade: 'A+' },
  { id: 'G04', roll: 'MU-2023-CS-0833', name: 'Aditya Deshmukh', midterm: 20.0, quiz: 9.5, project: 28.0, lab: 11.0, total: 68.5, grade: 'C+' },
  { id: 'G05', roll: 'MU-2023-CS-0850', name: 'Meera Nambiar', midterm: 27.0, quiz: 13.5, project: 35.0, lab: 14.0, total: 89.5, grade: 'A-' },
  { id: 'G06', roll: 'MU-2023-CS-0862', name: 'Arjun Sen', midterm: 25.0, quiz: 12.5, project: 33.0, lab: 13.5, total: 84.0, grade: 'B+' },
  { id: 'G07', roll: 'MU-2023-CS-0871', name: 'Pooja Hegde', midterm: 29.0, quiz: 14.0, project: 39.0, lab: 15.0, total: 97.0, grade: 'A+' },
  { id: 'G08', roll: 'MU-2023-CS-0888', name: 'Varun Grover', midterm: 26.0, quiz: 13.0, project: 34.0, lab: 14.0, total: 87.0, grade: 'B+' },
];

export const REGISTRAR_METRICS = {
  totalEnrolled: 14820,
  totalStudents: 14820,
  averageAttendance: 88.6,
  feeCollectionPercentage: 85.3,
  totalFeesCollected: '₹18.42 Cr',
  totalFeesExpected: '₹21.60 Cr',
  yoyGrowth: '+4.2%',
  feeCollection: '₹42,84,00,000',
  feeCollectionNumeric: 428400000,
  collectionRate: '94.6%',
  facultyCount: 822,
  facultyStudentRatio: '1 : 18',
  overallRetention: '96.8%',
  atRiskStudents: 68,
  activeAccreditations: 12,
  degreesAwardedYTD: 2840,
  totalCapacity: 16000,
};

export const ENROLLMENT_BY_SCHOOL = [
  { school: 'Computing & Data', enrolled: 4200, capacity: 4500, retention: 97.4, feeRealized: 96.2, avgGpa: 3.58 },
  { school: 'Engineering & Robotics', enrolled: 3650, capacity: 4000, retention: 95.8, feeRealized: 94.1, avgGpa: 3.42 },
  { school: 'Business & Management', enrolled: 3100, capacity: 3300, retention: 96.2, feeRealized: 95.5, avgGpa: 3.61 },
  { school: 'Health & Medical Tech', enrolled: 2250, capacity: 2400, retention: 98.1, feeRealized: 97.8, avgGpa: 3.72 },
  { school: 'Arts & Humanities', enrolled: 1620, capacity: 1800, retention: 94.5, feeRealized: 92.4, avgGpa: 3.49 },
];

export const FEE_COLLECTION_TRENDS = [
  { month: 'Oct 2025', collected: 7.2, expected: 7.5 },
  { month: 'Nov 2025', collected: 5.1, expected: 5.2 },
  { month: 'Dec 2025', collected: 3.4, expected: 3.5 },
  { month: 'Jan 2026', collected: 18.2, expected: 18.5 },
  { month: 'Feb 2026', collected: 5.4, expected: 5.5 },
  { month: 'Mar 2026', collected: 3.5, expected: 3.8 },
];

export const ATTENDANCE_DISTRIBUTION = [
  { bracket: '> 90% (Distinction)', count: 9640, percentage: 65.0, color: '#10B981' },
  { bracket: '80% - 90% (Good)', count: 3520, percentage: 23.8, color: '#2563EB' },
  { bracket: '75% - 80% (Borderline)', count: 1210, percentage: 8.2, color: '#F59E0B' },
  { bracket: '< 75% (Shortfall Warning)', count: 450, percentage: 3.0, color: '#EF4444' },
];

export const STUDENT_DIRECTORY = [
  {
    id: 'MU-2023-CS-0842',
    name: 'Aisha Sharma',
    school: 'School of Computing',
    program: 'B.Tech CSE',
    batch: '2023 - 2027',
    year: 'Year 3',
    gpa: '3.88',
    attendance: '91.4%',
    financialStatus: 'Pending ₹65,000',
    academicStatus: 'Honor Roll',
    riskLevel: 'Low',
    advisor: 'Prof. Raghav Iyer',
    hostel: 'Kaveri Residence Quad, #312',
    phone: '+91 98450 12842',
    email: 'aisha.sharma@meridian.edu',
  },
  {
    id: 'MU-2023-CS-0811',
    name: 'Kavya Ramanathan',
    school: 'School of Computing',
    program: 'B.Tech CSE',
    batch: '2023 - 2027',
    year: 'Year 3',
    gpa: '3.24',
    attendance: '88.0%',
    financialStatus: 'Paid in Full',
    academicStatus: 'Good Standing',
    riskLevel: 'Low',
    advisor: 'Prof. Raghav Iyer',
    hostel: 'Yamuna Tower, #104',
    phone: '+91 98221 54321',
    email: 'kavya.r@meridian.edu',
  },
  {
    id: 'MU-2023-CS-0833',
    name: 'Aditya Deshmukh',
    school: 'School of Computing',
    program: 'B.Tech CSE',
    batch: '2023 - 2027',
    year: 'Year 3',
    gpa: '2.54',
    attendance: '74.2%',
    financialStatus: 'Pending ₹1,40,000',
    academicStatus: 'Academic Warning',
    riskLevel: 'High',
    advisor: 'Prof. Raghav Iyer',
    hostel: 'Off Campus Resident (Indiranagar)',
    phone: '+91 97110 99887',
    email: 'aditya.d@meridian.edu',
  },
  {
    id: 'MU-2022-EE-0419',
    name: 'Priyanka Sen',
    school: 'School of Engineering',
    program: 'B.E. Electrical & Microelectronics',
    batch: '2022 - 2026',
    year: 'Year 4',
    gpa: '3.94',
    attendance: '97.0%',
    financialStatus: 'Merit Scholarship / Cleared',
    academicStatus: "Dean's Scholar",
    riskLevel: 'Low',
    advisor: 'Dr. Arthur Pendelton',
    hostel: 'Ganga Complex, #405',
    phone: '+91 94451 22334',
    email: 'priyanka.sen@meridian.edu',
  },
  {
    id: 'MU-2024-BBA-0190',
    name: 'Kabir Singhania',
    school: 'School of Business',
    program: 'BBA Global Finance',
    batch: '2024 - 2028',
    year: 'Year 2',
    gpa: '3.42',
    attendance: '89.5%',
    financialStatus: 'Paid in Full',
    academicStatus: 'Good Standing',
    riskLevel: 'Low',
    advisor: 'Prof. Evelyn Cross',
    hostel: 'Godavari Quad, #201',
    phone: '+91 98205 77665',
    email: 'kabir.s@meridian.edu',
  },
  {
    id: 'MU-2023-BIO-0512',
    name: 'Ananya Deshpande',
    school: 'School of Health Tech',
    program: 'B.S. Computational Biology',
    batch: '2023 - 2027',
    year: 'Year 3',
    gpa: '3.81',
    attendance: '93.2%',
    financialStatus: 'Paid in Full',
    academicStatus: 'Honor Roll',
    riskLevel: 'Low',
    advisor: 'Dr. Victor Frank',
    hostel: 'Saraswati Hall, #518',
    phone: '+91 99880 11223',
    email: 'ananya.d@meridian.edu',
  },
];

export const CONNECTED_SYSTEMS = [
  {
    id: 'lms',
    name: 'Canvas / Moodle LMS Synchronization',
    category: 'LMS',
    status: 'Operational',
    latency: '42ms',
    uptime: '99.98%',
    lastSync: '1 minute ago',
    description: 'Bi-directional roster, assignments, syllabus milestones, and continuous assessment gradebook sync.',
    type: 'Demo / Mock Integration',
  },
  {
    id: 'sis',
    name: 'PeopleSoft / Banner SIS Core Connector',
    category: 'SIS',
    status: 'Operational',
    latency: '34ms',
    uptime: '99.95%',
    lastSync: '5 minutes ago',
    description: 'Central student records, major declarations, academic probation holds, and degree certification.',
    type: 'Demo / Mock Integration',
  },
  {
    id: 'sso',
    name: 'Meridian University SAML 2.0 / OAuth2 SSO',
    category: 'SSO',
    status: 'Operational',
    latency: '18ms',
    uptime: '100.00%',
    lastSync: 'Real-time Auth Stream',
    description: 'Identity verification, multi-factor authentication (MFA), and role-based access control (RBAC).',
    type: 'Demo / Mock Integration',
  },
  {
    id: 'payments',
    name: 'Campus NetBanking & UPI Payment Gateway',
    category: 'Payment/Fees',
    status: 'Operational',
    latency: '110ms',
    uptime: '99.99%',
    lastSync: 'Real-time Webhook',
    description: 'Instant fee settlement, receipt reconciliation, late fee calculations, and installment plans.',
    type: 'Demo / Mock Integration',
  },
  {
    id: 'biometrics',
    name: 'RFID & Biometric Turnstile Gates',
    category: 'Hardware IoT',
    status: 'Operational',
    latency: '24ms',
    uptime: '99.85%',
    lastSync: 'Live WebSocket Stream',
    description: 'Lecture hall ingress, automated roll call validation, hostel curfew logging, and lab check-ins.',
    type: 'Demo / Mock Integration',
  },
  {
    id: 'koha',
    name: 'Koha Library ERP & IEEE Consortium',
    category: 'Library',
    status: 'Operational',
    latency: '85ms',
    uptime: '99.70%',
    lastSync: '14 minutes ago',
    description: 'Book reservations, fine ledger synchronization, and research journal repository quotas.',
    type: 'Demo / Mock Integration',
  },
];
